# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
GMAIL_USERNAME: punjabrav
GMAIL_PASSWORD: sharks11
S3_KEY: AKIAJBXTCGHDX5O4DTLQ
S3_SECRET: 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
S3_BUCKET_NAME: litigo
S3_REGION: us-east-1
DROPBOX_APP_KEY: "7sgh3y5p0fqu0kh"
DROPBOX_APP_KEY_SECRET: "47otytbrlftsl6d"
DROPBOX_APP_MODE: "dropbox"