S3_KEY: AKIAJBXTCGHDX5O4DTLQ
S3_SECRET: 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
S3_BUCKET_NAME: litigo
S3_REGION: us-east-1
DROPBOX_APP_KEY: "7sgh3y5p0fqu0kh"
DROPBOX_APP_KEY_SECRET: "47otytbrlftsl6d"
DROPBOX_APP_MODE: "dropbox"