development:
  adapter: postgresql
  encoding: unicode
  database: litigo_development
  pool: 5
  host: localhost
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: litigo_test
  pool: 5
  host: localhost
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: litigo_staging
  pool: 5
  username: postgres
  password:

production:
  host: localhost
  adapter: postgresql
  username: postgres
  password:
  encoding: unicode
  pool: 5

cucumber:
  <<: *test