class AddMissingIndexesForAll < ActiveRecord::Migration
  def up
  	add_index :time_entries, :user_id
  	add_index :time_entries, :case_id
  	add_index :templates, :user_id
  	add_index :templates, :firm_id
  	add_index :template_documents, :firm_id
  	add_index :template_documents, :user_id
  	add_index :tasks, :owner_id
  	add_index :tasks, :secondary_owner_id
  	add_index :tasks, :case_id
  	add_index :tasks, :parent_id
  	add_index :tasks, :task_draft_id
  	add_index :task_lists, :user_id
  	add_index :task_lists, :firm_id
  	add_index :task_drafts, :task_list_id
  	add_index :task_drafts, :parent_id
  	add_index :resolutions, :resolution_type
  	add_index :phones, :firm_id
  	add_index :phones, :contact_id
  	add_index :participants, :firm_id
  	add_index :namespaces, :firm_id
  	add_index :namespaces, :user_id
  	add_index :namespaces, :account_status
  	add_index :medical_bills, :firm_id
  	add_index :medical_bills, :user_id
  	add_index :medical_bills, :case_id
  	add_index :medical_bills, :medical_id
  	add_index :medical_bills, :parent_id
  	add_index :medical_bills, :company_id
  	add_index :leads, :firm_id
  	add_index :leads, :attorney_id
  	add_index :leads, :status 
  	add_index :leads, :contact_id
  	add_index :insurances, :firm_id
  	add_index :insurances, :case_id
  	add_index :insurances, :company_id
  	add_index :insurances, :insurance_provider
  	add_index :injuries, :case_id
  	add_index :injuries, :injury_type
  	add_index :injuries, :region
  	add_index :expenses, :firm_id
  	add_index :expenses, :user_id
  	add_index :events, :firm_id
  	add_index :events, :created_by
  	add_index :events, :last_updated_by
  	add_index :events, :event_series_id
  	add_index :events, :calendar_id
  	add_index :events, :namespace_id
  	add_index :events, :nylas_namespace_id
  	add_index :event_series, :firm_id
  	add_index :event_series, :frequency
  	add_index :event_series, :user_id
  	add_index :event_participants, :firm_id
  	add_index :contacts, :type
  	add_index :cases, :case_type
  	add_index :cases, :subtype
  	add_index :case_contacts, :firm_id
  	add_index :case_contacts, :case_id
  	add_index :case_contacts, :role
  	add_index :calendars, :firm_id
  	add_index :calendars, :namespace_id
  end

  def down
  	remove_index :time_entries, :user_id
  	remove_index :time_entries, :case_id
    remove_index :templates, :user_id
  	remove_index :templates, :firm_id
  	remove_index :template_documents, :firm_id
  	remove_index :template_documents, :user_id
  	remove_index :tasks, :owner_id
  	remove_index :tasks, :secondary_owner_id
  	remove_index :tasks, :case_id
  	remove_index :tasks, :parent_id
  	remove_index :tasks, :task_draft_id
  	remove_index :task_lists, :user_id
  	remove_index :task_lists, :firm_id
  	remove_index :task_drafts, :task_list_id
  	remove_index :task_drafts, :parent_id
  	remove_index :resolutions, :resolution_type
  	remove_index :phones, :firm_id
  	remove_index :phones, :contact_id
  	remove_index :participants, :firm_id
  	remove_index :namespaces, :firm_id
  	remove_index :namespaces, :user_id
  	remove_index :namespaces, :account_status
  	remove_index :medical_bills, :firm_id
  	remove_index :medical_bills, :user_id
  	remove_index :medical_bills, :case_id
  	remove_index :medical_bills, :medical_id
  	remove_index :medical_bills, :parent_id
  	remove_index :medical_bills, :company_id
  	remove_index :leads, :firm_id
  	remove_index :leads, :attorney_id
  	remove_index :leads, :status 
  	remove_index :leads, :contact_id
  	remove_index :insurances, :firm_id
  	remove_index :insurances, :case_id
  	remove_index :insurances, :company_id
  	remove_index :insurances, :insurance_provider
  	remove_index :injuries, :case_id
  	remove_index :injuries, :injury_type
  	remove_index :injuries, :region
  	remove_index :expenses, :firm_id
  	remove_index :expenses, :user_id
  	remove_index :events, :firm_id
  	remove_index :events, :created_by
  	remove_index :events, :last_updated_by
  	remove_index :events, :event_series_id
  	remove_index :events, :calendar_id
  	remove_index :events, :namespace_id
  	remove_index :events, :nylas_namespace_id
  	remove_index :event_series, :firm_id
  	remove_index :event_series, :frequency
  	remove_index :event_series, :user_id
  	remove_index :event_participants, :firm_id
  	remove_index :contacts, :type
  	remove_index :cases, :case_type
  	remove_index :cases, :subtype
  	remove_index :case_contacts, :firm_id
  	remove_index :case_contacts, :case_id
  	remove_index :case_contacts, :role
  	remove_index :calendars, :firm_id
  	remove_index :calendars, :namespace_id
  end
end
